---
apiVersion: v1
kind: Service
metadata:
  name: redis-torch
spec:
  selector:
    app: redis
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: redis
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2.3-alpine
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 750m
              memory: 100Mi
          ports:
            - containerPort: 6379
              name: redis
