---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: torch
  name: torch
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: torch
  type: ClusterIP
